2024-01-05 11:01:20,938 INFO    MainThread:25916 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-01-05 11:01:20,938 INFO    MainThread:25916 [wandb_setup.py:_flush():76] Configure stats pid to 25916
2024-01-05 11:01:20,938 INFO    MainThread:25916 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Susana\.config\wandb\settings
2024-01-05 11:01:20,938 INFO    MainThread:25916 [wandb_setup.py:_flush():76] Loading settings from c:\Users\Susana\Desktop\Universidad\Tercero\Primer\AA2\project\ConvolutionalNetwork\wandb\settings
2024-01-05 11:01:20,940 INFO    MainThread:25916 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-05 11:01:20,940 INFO    MainThread:25916 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-01-05 11:01:20,940 INFO    MainThread:25916 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-05 11:01:20,940 INFO    MainThread:25916 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\Susana\Desktop\Universidad\Tercero\Primer\AA2\project\ConvolutionalNetwork\wandb\run-20240105_110120-etrqul0b\logs\debug.log
2024-01-05 11:01:20,940 INFO    MainThread:25916 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\Susana\Desktop\Universidad\Tercero\Primer\AA2\project\ConvolutionalNetwork\wandb\run-20240105_110120-etrqul0b\logs\debug-internal.log
2024-01-05 11:01:20,941 INFO    MainThread:25916 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000151F03DF580>
2024-01-05 11:01:20,941 INFO    MainThread:25916 [wandb_init.py:init():564] calling init triggers
2024-01-05 11:01:20,941 INFO    MainThread:25916 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-01-05 11:01:20,941 INFO    MainThread:25916 [wandb_init.py:init():614] starting backend
2024-01-05 11:01:20,941 INFO    MainThread:25916 [wandb_init.py:init():618] setting up manager
2024-01-05 11:01:20,941 INFO    MainThread:25916 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-01-05 11:01:20,956 INFO    MainThread:25916 [wandb_init.py:init():624] backend started and connected
2024-01-05 11:01:20,962 INFO    MainThread:25916 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-01-05 11:01:20,962 INFO    MainThread:25916 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-01-05 11:01:20,962 INFO    MainThread:25916 [wandb_init.py:init():716] updated telemetry
2024-01-05 11:01:21,028 INFO    MainThread:25916 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-01-05 11:01:22,059 INFO    MainThread:25916 [wandb_run.py:_on_init():2254] communicating current version
2024-01-05 11:01:22,990 INFO    MainThread:25916 [wandb_run.py:_on_init():2263] got version response 
2024-01-05 11:01:22,990 INFO    MainThread:25916 [wandb_init.py:init():800] starting run threads in backend
2024-01-05 11:01:23,241 INFO    MainThread:25916 [wandb_run.py:_console_start():2233] atexit reg
2024-01-05 11:01:23,241 INFO    MainThread:25916 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2024-01-05 11:01:23,241 INFO    MainThread:25916 [wandb_run.py:_redirect():2153] Wrapping output streams.
2024-01-05 11:01:23,241 INFO    MainThread:25916 [wandb_run.py:_redirect():2178] Redirects installed.
2024-01-05 11:01:23,241 INFO    MainThread:25916 [wandb_init.py:init():841] run started, returning control to user process
2024-01-05 11:01:23,249 INFO    MainThread:25916 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-05 11:01:23,249 INFO    MainThread:25916 [wandb_init.py:_pause_backend():435] pausing backend
2024-01-05 11:01:23,271 INFO    MainThread:25916 [wandb_init.py:_resume_backend():440] resuming backend
2024-01-05 11:01:23,273 INFO    MainThread:25916 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-05 11:01:23,273 INFO    MainThread:25916 [wandb_init.py:_pause_backend():435] pausing backend
2024-01-05 11:01:26,903 INFO    MainThread:25916 [wandb_init.py:_resume_backend():440] resuming backend
2024-01-05 11:01:26,905 INFO    MainThread:25916 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-05 11:01:26,905 INFO    MainThread:25916 [wandb_init.py:_pause_backend():435] pausing backend
2024-01-05 11:01:27,430 INFO    MainThread:25916 [wandb_init.py:_resume_backend():440] resuming backend
2024-01-05 11:01:27,450 INFO    MainThread:25916 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-01-05 11:01:27,450 INFO    MainThread:25916 [wandb_setup.py:_flush():76] Configure stats pid to 25916
2024-01-05 11:01:27,450 INFO    MainThread:25916 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Susana\.config\wandb\settings
2024-01-05 11:01:27,450 INFO    MainThread:25916 [wandb_setup.py:_flush():76] Loading settings from c:\Users\Susana\Desktop\Universidad\Tercero\Primer\AA2\project\ConvolutionalNetwork\wandb\settings
2024-01-05 11:01:27,450 INFO    MainThread:25916 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-05 11:01:27,451 INFO    MainThread:25916 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-01-05 11:01:27,452 INFO    MainThread:25916 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-05 11:01:27,452 INFO    MainThread:25916 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\Susana\Desktop\Universidad\Tercero\Primer\AA2\project\ConvolutionalNetwork\wandb\run-20240105_110127-9wtrup0x\logs\debug.log
2024-01-05 11:01:27,452 INFO    MainThread:25916 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\Susana\Desktop\Universidad\Tercero\Primer\AA2\project\ConvolutionalNetwork\wandb\run-20240105_110127-9wtrup0x\logs\debug-internal.log
2024-01-05 11:01:27,452 INFO    MainThread:25916 [wandb_init.py:init():564] calling init triggers
2024-01-05 11:01:27,452 INFO    MainThread:25916 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-01-05 11:01:27,452 INFO    MainThread:25916 [wandb_init.py:init():589] re-initializing run, found existing run on stack: etrqul0b
2024-01-05 11:01:27,455 INFO    MainThread:25916 [wandb_run.py:_finish():1962] finishing run data2023/FaceRecognition/etrqul0b
2024-01-05 11:01:27,457 ERROR   MainThread:25916 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-01-05 11:01:27,457 INFO    MainThread:25916 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-05 11:01:27,457 INFO    MainThread:25916 [wandb_init.py:_jupyter_teardown():452] cleaning up jupyter logic
2024-01-05 11:01:27,457 INFO    MainThread:25916 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-01-05 11:01:27,457 INFO    MainThread:25916 [wandb_run.py:_restore():2185] restore
2024-01-05 11:01:27,457 INFO    MainThread:25916 [wandb_run.py:_restore():2191] restore done
2024-01-05 11:01:31,229 INFO    MainThread:25916 [wandb_run.py:_footer_history_summary_info():3837] rendering history
2024-01-05 11:01:31,229 INFO    MainThread:25916 [wandb_run.py:_footer_history_summary_info():3869] rendering summary
2024-01-05 11:01:31,235 INFO    MainThread:25916 [wandb_run.py:_footer_sync_info():3796] logging synced files
